### ISSUE TITLE
Message count indicator is always 'actual count + 1'

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#124]
I'm seeing this bug on my account ('atif') on deployed site. If you login, you'll see the message count indicator in the bottom navbar always showing a number which is actual unread message count + 1. For example:
- if no unread messages, count = 1
- if 3 unread messages, count = 4

The count next to 'Inbox' button on Messages page shows the correct figure. This may just be an issue with my account on the site specifically, or it may be a general bug -- I didn't see it on the test site though. Take a look.

**Comment by swash99** [comment]
It seems Zahid started a conversation with you on the 4th of December which is what was showing up as the 1 message.

Problem is this conversation had no message data in it which is why it wasnt showing up in your inbox.
This raises a few questions since you should not be able to start conversations without message data.

I haven't been able to replicate the issue on my end but I think this message was sent using an iphone(the title had iphone test in it) so if you want you can see if it can be recreated from there. 

Either way I can add another check and make sure no conversation is started without message data.

**Comment by sa31fh** [comment]
- I know Zahid was complaining about Messages not working on iPhone. It may be related to that.
- Yes, you should add all necessary checks at the start to ensure the message is what you expect it to be.
- However, I think the message should still be displayed if *somehow* it still got through without any data in it. At least then we can catch the problem and I, as a user, can delete the orphaned conversation. Right now, it neither shows up in the inbox and it still shows up in counter. Thats rather frustrating. Use your magic to fix this!

**Comment by swash99** [comment]
Couldn't really find any issues that could cause an empty conversation to be created. All the approriate checks were also in place. For now i've updated the sql query to show conversations even if they are empty.

**Comment by sa31fh** [comment]
If necessary checks are in place, then that should be sufficient for now.
The more important thing was the conversation not showing up in inbox, even if it was empty. At least if an empty message shows up you can track it and delete it. So thats still progress.
