### ISSUE TITLE
Add delete option for conversation/message

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#13]
Add delete option for conversations and/or messages. Also consider if some kind of auto-delete messages after some time (30 days?) thingy can be added. This would be appropriate as a procedure/function in the database, scheduled to run once a day.

**Comment by swash99** [comment]
Users can delete "Inbox" conversations now, which will be moved into the "Deleted" tab. However conversations and their respective messages are still not removed from the database. 

Since both "sender" and "receiver" act on the conversations individually, a conversation can not be removed from the database until both sides have deleted the conversation on their respective ends. A function can be added to check if a conversation has been deleted from both sides. 

Another function can be added to remove a conversation from the individual users "Deleted" tab after 'x' days even if its not removed from the database yet. This way both sides can delete their messages at their convenience and conversations can be permanently and safely removed from the database later.

To help with this, I was thinking we can have a "conversation_status" column holding varchar data rather than individual 'delete', 'read' etc colums with boolean values. This way we can specify a status for a conversation for each user e.g. 'unread', 'read' ,'deleted' etc. Then we just read the value and treat the message accordingly. Both 'sender' and 'receiver' will have their own "conversation_status" columns.

**Comment by sa31fh** [comment]
Information in databases is handled via relationship and constraints. The aim is to reduce duplication/redundancy and ensure accuracy. Some background knowledge base if you're interested:
https://en.wikipedia.org/wiki/Database_normalization
https://en.wikipedia.org/wiki/First_normal_form
https://en.wikipedia.org/wiki/Second_normal_form
https://en.wikipedia.org/wiki/Third_normal_form
https://en.wikipedia.org/wiki/Boyce%E2%80%93Codd_normal_form

Now if you add a conversation_status column holding varchar data with strings such as 'delete'/'read', there is high probability of things going wrong. For example, what if there is a typo and somehow 'raed' gets inserted instead of 'read'. That conversation status will just float around in limbo without anyone catching it.

What you want to do is create a new 'ConversationStatus' table. Columns:
id - int [auto-increment, primary key]
status - varchar [size 20 maybe? doesn't have to be too big since it'll be one word like 'delete' or 'read'.]

Now you add a column (as you mentioned) to track the status of a conversation -- but instead of varchar you link to the ConversationStatus row:
conversationstatus_id: int  [foreign key linking to ConversationStatus id column -- perhaps add cascading options e.g. what happens to the linked conversationstatus_id rows if a status is deleted in ConversationStatus table].

As for auto-deletion - You might be able to implement it as a procedure in the database which gets triggered when a conversation is deleted. Suggest you master stored procedure concept:
https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-stored-procedures.html
http://www.mysqltutorial.org/mysql-stored-procedure-tutorial.aspx

**Comment by swash99** [comment]
Yeah thats fine. The main idea is just to avoid making seperate columns for every messege status. A seperate status table is a good idea.

**Comment by swash99** [comment]
The ConversationStatus table has been added and respective changes have been made to the messages pages. 

The auto-delete function is still pending. After reading a bit about stored procedures and similar methods within mysql, I think two better options would either be CREATE EVENTS() or CREATE TRIGGERS(). Both events() and triggers() are designed more for what we want, modifiying tables and data after a certain change; a change that can either be time based (handled by events) or some sort of change in the database that is a trigger point like a table being updated (handled by triggers).

I did try creating an event and it was simple enough to make one. I'm not sure if there are any issues with using events() or triggers(). Mysql workbench has a visual interface to create triggers for each and any table. Overall I think these two may do the job if I've understood everything correctly.

**Comment by swash99** [comment]
To work in the current environment, a php based auto delete-conversation system has been set up. A date to remove each deleted conversation is set and on reaching that date the conversation status is set to 'destroy'. This visibly removes the conversation for a user while still keeping it in the database. Currently a conversation is 'destroyed' after 1 week.
