### ISSUE TITLE
All messages appear in the deleted tab

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#14]
All messages in the inbox also seem to appear in the deleted tab. Perhaps they appear after they are read?

**Comment by swash99** [comment]
Actually nothing appeared in the delete tab since there was no page link for it. On clicking it the page merely refreshed and took you back in the Inbox, hence seeing all the messages. A deleted message page as been added and selected tabs remain highlighted to display which tab a user is viewing to avoid confusion.
