### ISSUE TITLE
Messages do not show up in sent tab

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#15]
I sent a bunch of messages but none of them showed up in the sent tab. Maybe because the idea was to only display conversations in the sent tab but not outgoing messages replied in incoming conversations?

**Comment by swash99** [comment]
Yeah at the moment the sent tab only displays conversations started by the logged in user. Any messages sent within a conversation do not effect or update the results in the sent tab.

The need or purpose of a sent tab is still up for debate since the 'Inbox' is handling the bulk of the messaging, showing new conversations/updating old ones if new messages are added to them, showing unread and read messages etc.

**Comment by sa31fh** [comment]
If the sent tab is still not decided upon, I suggest we remove it from the side pane and keep an issue open in the backlog to track a possible future implementation. Its better to have fewer features which are implemented and working instead of a lot of half baked features thrown in the mix. It confuses the end user and reduces the 'wow' factor when the feature is finally implemented and deployed.

**Comment by sa31fh** [comment]
Closing this issue as invalid. If the need arises for a 'Sent' tab we can add that in the future. Currently this is not a very pressing.
