### ISSUE TITLE
Expected sales keeps moving down

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#24]
On category_status.php, if I click on one of the categories e.g. 'Drinks' for three or more times, the 'Expected Sales' field below the table starts moving down one line with every click on a category. It doesn't matter which category/ies are clicked on and in which order.

**Comment by swash99** [comment]
The issue was in the javascript function meant to auto adjust the height of the iframe on page load. The height value kept stacking each time a page was loaded rather than refreshing to a new value. The bug only seemed to occur in chrome browser and not in firefox. Issue has been resolved. Tested locally on both browsers.
