### ISSUE TITLE
Version 1.1.0: Finishing tasks

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#52]
- Push all changes and backup
- Rebase b1.1.0 to master
- Add v1.1.0 tag and push tag
- Verify rebasing and tagging was successful then delete b1.1.0 branch
- Update auntys site

**Comment by swash99** [comment]
- [x] All issues/bugs fixed in v1.1.0
- [x] Rebased with local master branch and pushed to origin master
- [x] v1.1.0 tag added to local master and pushed to origin master
- [x] All updates verified and deleted branch 1.1.0
- [x] Both auntys site and test site updated with latest changes and fixes
- [x] Created branch 1.2.0
