### ISSUE TITLE
Fix "cannot modify header information" error

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#6]
The following error is seen when I change the password:

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk4/2013511/www/auntyskitchen-ims.dx.am/change_password.php:27) in /srv/disk4/2013511/www/auntyskitchen-ims.dx.am/change_password.php on line 88

The password change itself works. Figure out the source of the error above and fix all instances of it throughout the site (presumably there are other instances since this was seen on the login page as well initially).

**Comment by swash99** [comment]
I figured out the issue while testing the website itself. It was just the placement of the header functions that was causing the issue. After moving them to the top of the file before any html data, the issue seems to be resolved. Not all files have for the website have been updated yet but the issue has been resolved locally.
