### ISSUE TITLE
Extra line pops up when duplicate category added

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#7]
In edit_categories.php, if I select an existing category and then click 'Add' button it refreshes the page and adds a blank line at the top. Very minor issue but it adds inconsistency. The extra line actually looks good so suggest you make that permanent.

**Comment by swash99** [comment]
It wasnt an extra line but rather an error message that was being hidden beneath the nav bar due to minor layout issues. The admin tasks section has been changed so the issue is no longer relevant and new layout has been checked to see if the error displays properly. Also added extra line to make it look good. Tested locally.
